### ISSUE TITLE
Some error in export to onnx

### ISSUE THREAD

**Issue by Halafz7** [sefaburakokcu/quantized-yolov5#49]
So I tried to train yolov5m-quant.yaml with coco128.yaml. When it's done, i want to export it but error come like this

Traceback (most recent call last):
  File "/content/quantized-yolov5/models/experimental.py", line 97, in attempt_load
    ema = ckpt['ema' if ckpt.get('ema') else 'model'].float()
KeyError: 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/quantized-yolov5/export.py", line 418, in <module>
    main(opt)
  File "/content/quantized-yolov5/export.py", line 406, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/quantized-yolov5/export.py", line 317, in run
    model = attempt_load(weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
  File "/content/quantized-yolov5/models/experimental.py", line 105, in attempt_load
    ema.load_state_dict(ckpt)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "model.13.m.0.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.13.m.1.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.17.m.0.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.17.m.1.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.20.m.0.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.20.m.1.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.23.m.0.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value", "model.23.m.1.quant_identity.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value". 
	size mismatch for model.24.m.0.weight: copying a param with shape torch.Size([255, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 192, 1, 1]).
	size mismatch for model.24.m.1.weight: copying a param with shape torch.Size([255, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 384, 1, 1]).
	size mismatch for model.24.m.2.weight: copying a param with shape torch.Size([255, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 768, 1, 1]).

Do you have some advice or suggestion about this error? Thankyou

**Comment by sefaburakokcu** [comment]
Hi @Halafz7,
Thank you for your interest. Can you share your command for exporting the model?

**Comment by Halafz7** [comment]
Sure, i ran it on Colab and saved the weights on my Gdrive

! python export.py --data coco128.yaml --weights /content/gdrive/MyDrive/models/CheckpointsYOLO/YOLOv5/yolov5medium/weights/last.pt --nodetect

**Comment by sefaburakokcu** [comment]
As the error states, you are trying to load weights from 80 classes into a model with only one class. However, your export arguments seem correct. 

I think that attempt_load could not found your model.yaml. Can you replace last.pt with best.pt in your arguments?

**Comment by Halafz7** [comment]
Won't the classes switch automatically during training?

I did replaced the weight with best.pt but still got the same error

**Comment by mokoe004** [comment]
> Won't the classes switch automatically during training?
> 
> I did replaced the weight with best.pt but still got the same error

Hey, could you find a solution for this problem?

**Comment by m7md5303** [comment]
@Halafz7 could ypu please provide the steps for your training on Colab?
Thanjs in advance

**Comment by Jjateen** [comment]
Hi, was anyone able to solve this issue?

**Comment by surajkarki66** [comment]
Hello, anyone find the solution?

**Comment by sefaburakokcu** [comment]
Hi! Could you share the full error log?
